# ----------------------------------------------------------------------- #
#                                                                         #
#                               YMAL文件语法                               #
#                       http://medai.icu/thread/677                       #
#                                                                         #
# ----------------------------------------------------------------------- #
model_root: models
model_name: resnet50
data_pattern: "F:\OnekeyDS\CT\crop_sur"
epoch: 50